In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../qc_data/zenoQC_distAlerts_ha.csv')

In [8]:
columns = ['b1']

In [5]:
adm0 = df[((df.GID_2.isnull()) & (df.GID_1.isnull()))]
adm1 = df[((df.GID_2.isnull()) & (~df.GID_1.isnull()))]
adm2 = df[~df.GID_2.isnull()]

In [10]:


adm2_2024 = adm2[columns]

adm2_2024.index = adm2.GID_2.str.rstrip('_1')
adm2_2024.head()

                  b1
GID_2
COD.6.10   41.307948
COD.6.10  430.549834
COD.6.10   47.693307
COD.6.10  165.344775
COD.6.10  261.885620

In [11]:
adm1_2024 = adm1[columns]

adm1_2024.index = adm1.GID_1.str.rstrip('_1')
adm1_2024.head()

                 b1
GID_1
MYS.13   127.189207
MYS.13   328.261122
MYS.13  1149.545797
MYS.13   100.514811
MYS.13     0.000000

In [12]:
adm0_2024 = adm0[columns]

adm0_2024.index = adm0.GID_0.str.rstrip('_1')
adm0_2024.head()

                b1
GID_0
CZE      68.993844
CZE    1355.841257
CZE     243.048285
CZE    1932.935807
CZE     396.655753

In [13]:
qc_adm0 = adm0_2024.groupby(level=0).sum()
qc_adm1 = adm1_2024.groupby(level=0).sum()
qc_adm2 = adm2_2024.groupby(level=0).sum()

In [14]:
qc_adm0.rename(columns={'b1': 'area'}, inplace=True)

qc_adm1.rename(columns={'b1': 'area'}, inplace=True)

qc_adm2.rename(columns={'b1': 'area'}, inplace=True)

In [15]:
qc_adm2.head()

                   area
GID_2
COD.6.10    1554.196565
IDN.14.13    958.952121
PER.18.3   12504.657559

In [27]:
api_adm2_results = {
    "data": {
        "result": {
            "country": [
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "COD",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "IDN",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER",
                "PER"
            ],
            "region": [
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18,
                18
            ],
            "subregion": [
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3
            ],
            "alert_date": [
                "2025-06-11",
                "2025-06-11",
                "2025-06-12",
                "2025-06-12",
                "2025-06-13",
                "2025-06-13",
                "2025-06-15",
                "2025-06-15",
                "2025-06-20",
                "2025-06-20",
                "2025-06-23",
                "2025-06-23",
                "2025-06-25",
                "2025-06-25",
                "2025-06-26",
                "2025-06-26",
                "2025-06-27",
                "2025-06-27",
                "2025-06-28",
                "2025-06-28",
                "2025-06-30",
                "2025-06-30",
                "2025-06-11",
                "2025-06-11",
                "2025-06-16",
                "2025-06-16",
                "2025-06-17",
                "2025-06-17",
                "2025-06-18",
                "2025-06-18",
                "2025-06-21",
                "2025-06-21",
                "2025-06-26",
                "2025-06-26",
                "2025-06-29",
                "2025-06-29",
                "2025-06-01",
                "2025-06-01",
                "2025-06-11",
                "2025-06-11",
                "2025-06-12",
                "2025-06-12",
                "2025-06-13",
                "2025-06-13",
                "2025-06-14",
                "2025-06-14",
                "2025-06-17",
                "2025-06-17",
                "2025-06-19",
                "2025-06-19",
                "2025-06-20",
                "2025-06-20",
                "2025-06-21",
                "2025-06-21",
                "2025-06-22",
                "2025-06-22",
                "2025-06-24",
                "2025-06-27",
                "2025-06-28",
                "2025-06-28",
                "2025-06-29",
                "2025-06-29"
            ],
            "confidence": [
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "low",
                "high",
                "high",
                "low",
                "high",
                "low"
            ],
            "value": [
                1955838.0,
                2050117.375,
                2124947.0,
                403796.15625,
                78452.625,
                369122.84375,
                832985.375,
                722200.625,
                752108.5625,
                632167.8125,
                371510.90625,
                805277.0625,
                887589.75,
                960606.375,
                11536.2138671875,
                578335.4375,
                72297.921875,
                8721749.0,
                17687.197265625,
                16916.41015625,
                769.1162109375,
                31532.400390625,
                385013.09375,
                630002.8125,
                561012.0625,
                2189042.5,
                20764.30859375,
                27684.8203125,
                371860.21875,
                796630.4375,
                1852957.75,
                1110487.75,
                1049747.75,
                2931514.0,
                1538.27392578125,
                6153.1171875,
                2260.72216796875,
                591071.6875,
                4514.75927734375,
                5267.01025390625,
                752.8199462890625,
                389387.21875,
                3956872.75,
                95522944.0,
                93288.5546875,
                27069.828125,
                2913964.25,
                6827024.5,
                1771469.5,
                844178.0,
                15105.3427734375,
                73987.0625,
                272953.71875,
                29365.5546875,
                2877137.75,
                339792.09375,
                13578.91015625,
                4525.748046875,
                17371.392578125,
                30211.44921875,
                5328261.5,
                3169695.75
            ],
            "aoi_id": [
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3"
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin"
            ]
        },
        "metadata": {
            "aoi": {
                "ids": [
                    "COD.6.10",
                    "IDN.14.13",
                    "PER.18.3"
                ],
                "provider": "gadm",
                "type": "admin",
                "version": "4.1"
            },
            "end_date": "2025-06-30",
            "intersections": [],
            "start_date": "2025-06-01"
        },
        "message": None,
        "status": "saved"
    },
    "status": "success"
}

api_adm2 = pd.DataFrame(api_adm2_results['data']['result'])
api_adm2.set_index('aoi_id', drop=True, inplace=True)
api_adm2.drop('aoi_type', inplace=True, axis=1)

In [28]:
api_adm2 = api_adm2[['value']].rename(columns={'value': 'area'}).groupby(level=0).sum() / 1e4

In [29]:
api_adm2

                   area
aoi_id
COD.6.10    2239.754417
IDN.14.13   1193.440890
PER.18.3   12512.205187

In [26]:
qc_adm2

                   area
GID_2
COD.6.10    1554.196565
IDN.14.13    958.952121
PER.18.3   12504.657559

#### ADMIN 2 diffs

In [30]:
np.abs(api_adm2 - qc_adm2) / qc_adm2 * 100

                area
aoi_id
COD.6.10   44.110112
IDN.14.13  24.452604
PER.18.3    0.060359

In [46]:
api_adm1_results = {
    "data": {
        "result": {
            "country": [
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "MYS",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "SUR",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA"
            ],
            "region": [
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6
            ],
            "alert_date": [
                "2025-06-01",
                "2025-06-01",
                "2025-06-12",
                "2025-06-12",
                "2025-06-13",
                "2025-06-13",
                "2025-06-15",
                "2025-06-15",
                "2025-06-16",
                "2025-06-16",
                "2025-06-18",
                "2025-06-18",
                "2025-06-19",
                "2025-06-19",
                "2025-06-20",
                "2025-06-20",
                "2025-06-21",
                "2025-06-22",
                "2025-06-22",
                "2025-06-23",
                "2025-06-23",
                "2025-06-25",
                "2025-06-25",
                "2025-06-26",
                "2025-06-27",
                "2025-06-27",
                "2025-06-28",
                "2025-06-28",
                "2025-06-29",
                "2025-06-29",
                "2025-06-12",
                "2025-06-12",
                "2025-06-13",
                "2025-06-13",
                "2025-06-15",
                "2025-06-15",
                "2025-06-17",
                "2025-06-17",
                "2025-06-19",
                "2025-06-19",
                "2025-06-20",
                "2025-06-21",
                "2025-06-21",
                "2025-06-22",
                "2025-06-22",
                "2025-06-25",
                "2025-06-25",
                "2025-06-27",
                "2025-06-27",
                "2025-06-28",
                "2025-06-28",
                "2025-06-29",
                "2025-06-29",
                "2025-06-30",
                "2025-06-30",
                "2025-06-01",
                "2025-06-01",
                "2025-06-11",
                "2025-06-11",
                "2025-06-12",
                "2025-06-12",
                "2025-06-13",
                "2025-06-13",
                "2025-06-14",
                "2025-06-14",
                "2025-06-15",
                "2025-06-15",
                "2025-06-16",
                "2025-06-16",
                "2025-06-17",
                "2025-06-17",
                "2025-06-18",
                "2025-06-18",
                "2025-06-19",
                "2025-06-19",
                "2025-06-20",
                "2025-06-20",
                "2025-06-21",
                "2025-06-21",
                "2025-06-22",
                "2025-06-22",
                "2025-06-23",
                "2025-06-23",
                "2025-06-24",
                "2025-06-24",
                "2025-06-25",
                "2025-06-26",
                "2025-06-26",
                "2025-06-27",
                "2025-06-27",
                "2025-06-28",
                "2025-06-28",
                "2025-06-29",
                "2025-06-29",
                "2025-06-30",
                "2025-06-30"
            ],
            "confidence": [
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low"
            ],
            "value": [
                52083.6796875,
                1532.06298828125,
                7439074.0,
                1595303.375,
                24841570.0,
                5252419.5,
                731628.0,
                89617.7890625,
                134822.21875,
                5362.0693359375,
                4468577.0,
                995853.6875,
                2516209.25,
                758275.375,
                13881071.0,
                2532533.0,
                766.2258911132812,
                1394839.625,
                255828.921875,
                7408352.5,
                1750521.875,
                12527882.0,
                6662579.0,
                232871.125,
                8722351.0,
                1303195.375,
                20332716.0,
                5622314.0,
                3196010.5,
                5176821.5,
                402748.375,
                1668717.375,
                779151.5,
                842394.125,
                10729.705078125,
                147950.5,
                447659.46875,
                494842.78125,
                422585.34375,
                1732773.25,
                21502.720703125,
                617489.8125,
                920086.0625,
                788517.625,
                2251146.0,
                4609.05029296875,
                252471.75,
                305988.0,
                2102475.0,
                16867.8359375,
                782743.625,
                485388.71875,
                2166856.0,
                44485.12890625,
                1031049.375,
                11798383.0,
                1314168.625,
                10063971.0,
                750832.0625,
                26036458.0,
                545893.6875,
                36692676.0,
                1795049.375,
                34824136.0,
                1138627.625,
                4940505.5,
                257296.96875,
                4454875.5,
                412090.625,
                5778832.0,
                304165.71875,
                1395657.875,
                164640.828125,
                15789745.0,
                721411.75,
                5259633.5,
                222923.640625,
                57100644.0,
                4045789.5,
                6783555.5,
                749691.125,
                3725149.75,
                50273.42578125,
                7549372.0,
                515781.6875,
                4097.86962890625,
                6985017.0,
                66271.0703125,
                9488302.0,
                914338.125,
                14064035.0,
                707788.875,
                21021366.0,
                2154382.5,
                13172255.0,
                1730095.75
            ],
            "aoi_id": [
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6"
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin"
            ]
        },
        "metadata": {
            "aoi": {
                "ids": [
                    "MYS.13",
                    "SUR.9",
                    "USA.6"
                ],
                "provider": "gadm",
                "type": "admin",
                "version": "4.1"
            },
            "end_date": "2025-06-30",
            "intersections": [],
            "start_date": "2025-06-01"
        },
        "message": None,
        "status": "saved"
    },
    "status": "success"
}

api_adm1 = pd.DataFrame(api_adm1_results['data']['result'])
api_adm1.set_index('aoi_id', drop=True, inplace=True)
api_adm1.drop('aoi_type', inplace=True, axis=1)

In [47]:
api_adm1 = api_adm1[['value']].rename(columns={'value': 'area'}).groupby(level=0).sum() / 1e4

In [48]:
api_adm1

                area
aoi_id
MYS.13  13988.298166
SUR.9    1874.122913
USA.6   31549.018046

In [49]:
qc_adm1

                area
GID_1
MYS.13  11527.679148
SUR.9    1384.386228
USA.6   27873.509772

In [45]:
np.abs(api_adm1 - qc_adm1) / qc_adm1 * 100

             area
aoi_id
MYS.13  21.345311
SUR.9   35.375726
USA.6   13.186385

In [37]:
qc_adm0

               area
GID_0
CZE    35345.293435
GMB      144.977426
NZL    61216.587630

In [40]:
api_adm0_results = {
    "data": {
        "result": {
            "country": [
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL"
            ],
            "alert_date": [
                "2025-06-01",
                "2025-06-01",
                "2025-06-11",
                "2025-06-11",
                "2025-06-12",
                "2025-06-12",
                "2025-06-13",
                "2025-06-13",
                "2025-06-14",
                "2025-06-14",
                "2025-06-15",
                "2025-06-15",
                "2025-06-16",
                "2025-06-16",
                "2025-06-17",
                "2025-06-17",
                "2025-06-18",
                "2025-06-18",
                "2025-06-19",
                "2025-06-19",
                "2025-06-20",
                "2025-06-20",
                "2025-06-21",
                "2025-06-21",
                "2025-06-22",
                "2025-06-23",
                "2025-06-23",
                "2025-06-24",
                "2025-06-24",
                "2025-06-25",
                "2025-06-25",
                "2025-06-26",
                "2025-06-26",
                "2025-06-27",
                "2025-06-27",
                "2025-06-28",
                "2025-06-28",
                "2025-06-29",
                "2025-06-29",
                "2025-06-30",
                "2025-06-30",
                "2025-06-02",
                "2025-06-12",
                "2025-06-13",
                "2025-06-14",
                "2025-06-14",
                "2025-06-15",
                "2025-06-15",
                "2025-06-17",
                "2025-06-20",
                "2025-06-20",
                "2025-06-22",
                "2025-06-22",
                "2025-06-24",
                "2025-06-24",
                "2025-06-25",
                "2025-06-25",
                "2025-06-27",
                "2025-06-27",
                "2025-06-29",
                "2025-06-29",
                "2025-06-30",
                "2025-06-30",
                "2025-06-01",
                "2025-06-01",
                "2025-06-11",
                "2025-06-11",
                "2025-06-12",
                "2025-06-12",
                "2025-06-13",
                "2025-06-13",
                "2025-06-14",
                "2025-06-14",
                "2025-06-15",
                "2025-06-15",
                "2025-06-16",
                "2025-06-16",
                "2025-06-17",
                "2025-06-17",
                "2025-06-18",
                "2025-06-18",
                "2025-06-19",
                "2025-06-19",
                "2025-06-20",
                "2025-06-20",
                "2025-06-21",
                "2025-06-21",
                "2025-06-22",
                "2025-06-22",
                "2025-06-23",
                "2025-06-23",
                "2025-06-24",
                "2025-06-24",
                "2025-06-25",
                "2025-06-25",
                "2025-06-26",
                "2025-06-27",
                "2025-06-27",
                "2025-06-28",
                "2025-06-28",
                "2025-06-29",
                "2025-06-29",
                "2025-06-30",
                "2025-06-30"
            ],
            "confidence": [
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "high",
                "high",
                "high",
                "low",
                "high",
                "low",
                "high",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low",
                "high",
                "low"
            ],
            "value": [
                1728335.5,
                107565.9921875,
                24795596.0,
                4286625.0,
                20251806.0,
                7979817.5,
                68486136.0,
                55684892.0,
                123116.8671875,
                20078.75,
                4394856.5,
                7887867.5,
                137524.125,
                8961.9951171875,
                2208242.75,
                2384501.25,
                4370667.0,
                5852927.5,
                6761509.5,
                5821612.0,
                31630416.0,
                25385394.0,
                9072382.0,
                6254066.0,
                2516.40673828125,
                589184.1875,
                632070.75,
                1339957.625,
                1034647.5625,
                13347325.0,
                2877119.25,
                9315197.0,
                1573585.5,
                3735678.0,
                245267.125,
                18486216.0,
                6343368.0,
                3002.711669921875,
                46478.1640625,
                46592416.0,
                15193582.0,
                2997.9013671875,
                748.3976440429688,
                7492.8828125,
                214120.515625,
                16487.380859375,
                5243.70751953125,
                10482.4326171875,
                18725.9140625,
                68947.421875,
                83190.171875,
                512159.8125,
                170087.9375,
                210381.15625,
                131066.140625,
                7489.822265625,
                1499.343505859375,
                76348.703125,
                50930.7890625,
                253825.140625,
                644910.9375,
                6735.27294921875,
                19463.951171875,
                28730166.0,
                32385394.0,
                7002007.5,
                11108556.0,
                2714642.0,
                6922376.0,
                40433416.0,
                45480256.0,
                32566420.0,
                42106892.0,
                19254570.0,
                34922424.0,
                32049696.0,
                24359426.0,
                8346024.5,
                10663596.0,
                2674711.0,
                4283995.0,
                2706698.75,
                32874778.0,
                554634.5625,
                1937311.625,
                16450529.0,
                24355406.0,
                38885044.0,
                35335280.0,
                13527816.0,
                23562226.0,
                1200286.75,
                2049081.125,
                91614.546875,
                225493.4375,
                66591.125,
                557.629150390625,
                7240.68896484375,
                3632106.75,
                6463601.0,
                20642834.0,
                57945140.0,
                2285305.5,
                7836341.5
            ],
            "aoi_id": [
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL"
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin"
            ]
        },
        "metadata": {
            "aoi": {
                "ids": [
                    "CZE",
                    "GMB",
                    "NZL"
                ],
                "provider": "gadm",
                "type": "admin",
                "version": "4.1"
            },
            "end_date": "2025-06-30",
            "intersections": [],
            "start_date": "2025-06-01"
        },
        "message": None,
        "status": "saved"
    },
    "status": "success"
}

api_adm0 = pd.DataFrame(api_adm0_results['data']['result'])
api_adm0.set_index('aoi_id', drop=True, inplace=True)
api_adm0.drop('aoi_type', inplace=True, axis=1)

In [41]:
api_adm0 = api_adm0[['value']].rename(columns={'value': 'area'}).groupby(level=0).sum() / 1e4

In [42]:
api_adm0

                area
aoi_id
CZE     41699.250901
GMB       251.333573
NZL     67864.048599

In [43]:
qc_adm0

               area
GID_0
CZE    35345.293435
GMB      144.977426
NZL    61216.587630

In [44]:
np.abs(api_adm0 - qc_adm0) / qc_adm0 * 100

             area
aoi_id
CZE     17.976813
GMB     73.360488
NZL     10.858921