In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../qc_data/zenoQC_naturalLands_ha.csv')

In [4]:
df.columns.values

array(['system:index', 'ADM_LEVEL', 'CC_2', 'COUNTRY', 'COUNTRY_NO',
       'ENGTYPE_2', 'FID_TCL_QC', 'FID_world_', 'GID_0', 'GID_1', 'GID_2',
       'HASC_2', 'ISDISPUTED', 'Id', 'MAX_LEVEL', 'NAME_0', 'NAME_0_NOR',
       'NAME_1', 'NAME_1_NOR', 'NAME_2', 'NAME_2_NOR', 'NL_NAME_1',
       'NL_NAME_2', 'SIZE', 'TYPE_2', 'VARNAME_2', 'built', 'crop',
       'mangrove', 'natBare', 'natForest', 'natShortVeg', 'natWater',
       'nonNatBare', 'nonNatPeatShortVeg', 'nonNatPeatTree',
       'nonNatShortVeg', 'nonNatTree', 'nonNatWater', 'nonNatWetShortVeg',
       'nonNatWetTree', 'peatNatForest', 'peatNatShortVeg', 'snow',
       'wetNatForest', 'wetNatShortVeg'], dtype=object)

In [5]:
adm0 = df[((df.GID_2.isnull()) & (df.GID_1.isnull()))]
adm1 = df[((df.GID_2.isnull()) & (~df.GID_1.isnull()))]
adm2 = df[~df.GID_2.isnull()]

In [16]:
columns = df.columns[26:].values.tolist()
columns

['built',
 'crop',
 'mangrove',
 'natBare',
 'natForest',
 'natShortVeg',
 'natWater',
 'nonNatBare',
 'nonNatPeatShortVeg',
 'nonNatPeatTree',
 'nonNatShortVeg',
 'nonNatTree',
 'nonNatWater',
 'nonNatWetShortVeg',
 'nonNatWetTree',
 'peatNatForest',
 'peatNatShortVeg',
 'snow',
 'wetNatForest',
 'wetNatShortVeg']

In [17]:
adm2_2024 = adm2[columns]

adm2_2024.index = adm2.GID_2.str.rstrip('_1')
adm2_2024.head()

,built,crop,mangrove,natBare,natForest,natShortVeg,natWater,nonNatBare,nonNatPeatShortVeg,nonNatPeatTree,nonNatShortVeg,nonNatTree,nonNatWater,nonNatWetShortVeg,nonNatWetTree,peatNatForest,peatNatShortVeg,snow,wetNatForest,wetNatShortVeg
GID_2,,,,,,,,,,,,,,,,,,,,
COD.6.10,0.000000,0.000000,0.0,0.000000,2.185001e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,143.847983,0.000000
COD.6.10,49.847559,135.543566,0.0,178.770523,4.466042e+05,872.870111,1110.613571,0.153852,0.000000,1.923060,3.923214,371.476573,0.0,0.000000,0.999982,9770.406713,286.154844,0.0,13781.465554,53.692378
COD.6.10,2045.031586,18168.254444,0.0,65.384430,8.478505e+04,4148.579928,370.233866,0.000000,40.462402,155.695751,3707.367271,50788.057506,0.0,17.462293,46.308940,2181.415696,346.775581,0.0,329.233492,58.077481
COD.6.10,1585.152447,40.069490,0.0,117.046634,2.938995e+05,2460.356545,1261.858297,3.998880,0.000000,0.153824,13.150110,30.762342,0.0,0.000000,0.000000,9032.004794,134.275276,0.0,4560.395904,45.374840
COD.6.10,1598.399515,231.966053,0.0,607.769800,1.095087e+06,2333.357368,5120.596296,3.922498,0.230736,4.230214,5.306465,613.972596,0.0,0.000000,2.461095,17920.908724,904.620965,0.0,16999.300260,228.355164

In [18]:
adm1_2024 = adm1[columns]

adm1_2024.index = adm1.GID_1.str.rstrip('_1')
adm1_2024.head()

,built,crop,mangrove,natBare,natForest,natShortVeg,natWater,nonNatBare,nonNatPeatShortVeg,nonNatPeatTree,nonNatShortVeg,nonNatTree,nonNatWater,nonNatWetShortVeg,nonNatWetTree,peatNatForest,peatNatShortVeg,snow,wetNatForest,wetNatShortVeg
GID_1,,,,,,,,,,,,,,,,,,,,
MYS.13,5486.552730,11967.349580,84.389198,235.155042,280005.347728,1111.497012,349.658188,20.626705,17.325331,129.556152,1033.994705,35744.009782,0.000000,13.185029,61.018527,5642.413287,184.916331,0.0,589.849413,45.840610
MYS.13,7948.807313,9848.929278,0.000000,468.761880,750774.896906,4265.734655,592.890535,109.034971,15.948416,59.048297,1275.548441,20414.454752,0.000000,11.882898,43.312294,6343.709023,184.210077,0.0,524.894417,122.927350
MYS.13,24483.652476,125412.615866,34450.226779,1484.615935,518911.749819,6882.417469,2339.809072,208.301847,172.816792,750.579269,12969.250009,147104.955123,4.297098,208.008016,736.468677,5017.220724,406.814593,0.0,951.844426,158.981522
MYS.13,20975.019046,160035.203010,20934.557398,939.252595,80341.056776,794.721894,6971.139673,35.205695,362.099053,1363.156987,6317.971938,52795.812665,0.000000,238.318067,1373.449788,3003.813077,911.406708,0.0,2359.044685,446.441583
MYS.13,0.000000,0.000000,0.000000,7.591050,0.153358,10.121502,15.795407,0.460099,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.536752,2.453700,0.0,0.153358,6.824492

In [21]:
adm0_2024 = adm0[columns]

adm0_2024.index = adm0.GID_0.str.rstrip('_1')
adm0_2024.head()

,built,crop,mangrove,natBare,natForest,natShortVeg,natWater,nonNatBare,nonNatPeatShortVeg,nonNatPeatTree,nonNatShortVeg,nonNatTree,nonNatWater,nonNatWetShortVeg,nonNatWetTree,peatNatForest,peatNatShortVeg,snow,wetNatForest,wetNatShortVeg
GID_0,,,,,,,,,,,,,,,,,,,,
CZE,6773.114599,12904.163313,0.0,18.219685,14481.411903,1777.759793,183.015675,0.255294,17.228046,526.898242,1220.696001,27394.067920,0.0,0.306532,28.255878,243.472578,14.314709,0.0,76.377497,2.704301
CZE,60453.599681,89268.867750,0.0,117.887303,32426.979702,3867.884098,8212.523522,0.254908,64.704596,1823.914321,3515.649241,85842.912628,0.0,19.257731,84.111049,367.896444,60.521986,0.0,70.779689,79.158910
CZE,12642.974725,31516.906640,0.0,38.733958,11520.224012,632.630629,762.049969,0.152688,9.869597,293.074924,1373.002366,6477.719814,0.0,0.560187,2.393082,5.088035,1.781039,0.0,17.583980,12.231987
CZE,35000.821177,142715.294228,0.0,82.726111,20138.222151,2145.628472,4833.515955,0.000000,0.000000,0.000000,448.287352,1944.827927,0.0,17.957751,130.566815,0.000000,0.000000,0.0,712.461887,222.308216
CZE,17110.018604,57131.282337,0.0,67.631179,21696.286667,1583.958808,733.296692,0.101788,0.000000,0.000000,520.904263,8320.993957,0.0,4.635761,101.446516,23.826264,4.499477,0.0,284.067131,60.279179

In [39]:
qc_adm0 = adm0_2024.groupby(level=0).sum()
qc_adm1 = adm1_2024.groupby(level=0).sum()
qc_adm2 = adm2_2024.groupby(level=0).sum()

In [40]:
column_mapping =  {
    'built': "Built-up",
    'crop': "Cropland", 
    'mangrove': "Mangroves",
    'natBare': "Bare",
    'natForest': "Natural forests",
    'natShortVeg': "Natural short vegetation",
    'natWater': "Natural water",
    'nonNatBare': "Non-natural bare",
    'nonNatPeatShortVeg': "Non-natural peat short vegetation",
    'nonNatPeatTree': "Non-natural peat tree cover",
    'nonNatShortVeg': "Non-natural short vegetation",
    'nonNatTree': "Non-natural tree cover",
    'nonNatWater': "Non-natural water",
    'nonNatWetShortVeg': "Wetland non-natural short vegetation",
    'nonNatWetTree': "Wetland non-natural tree cover",
    'peatNatForest': "Natural peat forests",
    'peatNatShortVeg': "Natural peat short vegetation",
    'snow': "Snow",
    'wetNatForest': "Wetland natural forests",
    'wetNatShortVeg': "Wetland natural short vegetation"
}

qc_adm0.rename(columns=column_mapping, inplace=True)

qc_adm1.rename(columns=column_mapping, inplace=True)

qc_adm2.rename(columns=column_mapping, inplace=True)

In [28]:
api_adm2_results = {
    "data": {
        "result": {
            "natural_lands_class": [
                "Bare",
                "Built-up",
                "Cropland",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Non-natural peat short vegetation",
                "Non-natural peat tree cover",
                "Non-natural tree cover",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Wetland non-natural short vegetation",
                "Wetland non-natural tree cover",
                "Bare",
                "Built-up",
                "Cropland",
                "Mangroves",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural peat tree cover",
                "Non-natural tree cover",
                "Non-natural water",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Bare",
                "Built-up",
                "Cropland",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Non-natural peat short vegetation",
                "Wetland natural forests",
                "Wetland natural short vegetation"
            ],
            "value": [
                13432818,
                79961744,
                219328432,
                17235439616,
                515979968,
                22706982,
                222101600,
                91117880,
                84596.921875,
                37406776,
                406929.3125,
                1835377.625,
                568874432,
                417531872,
                5196495,
                174622.40625,
                521544.4375,
                48551512,
                33536560,
                35092384,
                3836173.25,
                7144766976,
                1009753088,
                3081965568,
                1303954432,
                205553920,
                290001440,
                3041037568,
                14977572,
                8448.3994140625,
                934016832,
                144295616,
                347490144,
                1104458112,
                24742449152,
                2245299200,
                80706784,
                9756.806640625,
                501469696,
                750.677001953125,
                79038728,
                310195.40625,
                3954487808,
                136600560
            ],
            "aoi_id": [
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "COD.6.10",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "IDN.14.13",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3",
                "PER.18.3"
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin"
            ]
        },
        "metadata": {
            "aoi": {
                "ids": [
                    "COD.6.10",
                    "IDN.14.13",
                    "PER.18.3"
                ],
                "provider": "gadm",
                "type": "admin",
                "version": "4.1"
            }
        },
        "message": None,
        "status": "saved"
    },
    "status": "success"
}

api_adm2 = pd.DataFrame(api_adm2_results['data']['result'])
api_adm2.set_index('aoi_id', drop=True, inplace=True)
api_adm2.drop('aoi_type', inplace=True, axis=1)

In [31]:
api_adm2 = api_adm2.pivot(columns='natural_lands_class', values='value') / 1e4

In [32]:
api_adm2.head()

natural_lands_class,Bare,Built-up,Cropland,Mangroves,Natural forests,Natural peat forests,Natural peat short vegetation,Natural short vegetation,Natural water,Non-natural bare,Non-natural hhort vegetation,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural tree cover,Non-natural water,Wetland natural forests,Wetland natural short vegetation,Wetland non-natural short vegetation,Wetland non-natural tree cover
aoi_id,,,,,,,,,,,,,,,,,,,
COD.6.10,1343.2818,7996.1744,21932.8432,NaN,1.723544e+06,51597.9968,2270.6982,22210.160000,9111.7880,8.459692,3740.6776,40.692931,183.537763,56887.4432,NaN,41753.18720,519.6495,17.462241,52.154444
IDN.14.13,4855.1512,3353.6560,3509.2384,383.617325,7.144767e+05,100975.3088,308196.5568,130395.443200,20555.3920,NaN,NaN,NaN,29000.144000,304103.7568,1497.7572,0.84484,93401.6832,NaN,NaN
PER.18.3,14429.5616,34749.0144,110445.8112,NaN,2.474245e+06,224529.9200,8070.6784,0.975681,50146.9696,0.075068,7903.8728,31.019541,NaN,NaN,NaN,395448.78080,13660.0560,NaN,NaN

In [43]:
qc_adm2.head()

,Built-up,Cropland,Mangroves,Bare,Natural forests,Natural short vegetation,Natural water,Non-natural bare,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural short vegetation,Non-natural tree cover,Non-natural water,Wetland non-natural short vegetation,Wetland non-natural tree cover,Natural peat forests,Natural peat short vegetation,Snow,Wetland natural forests,Wetland natural short vegetation
GID_2,,,,,,,,,,,,,,,,,,,,
COD.6.10,8001.506927,21960.714943,0.000000,1343.597407,3.337896e+06,22238.275524,9119.189893,8.459700,40.693138,183.538053,3739.974935,56972.030373,0.00000,17.462293,52.154379,51666.418383,2270.324298,0.0,41812.069769,519.707402
IDN.14.13,3353.266685,3509.361290,383.611777,4854.855684,6.628431e+05,130481.735402,20560.073156,0.000000,0.000000,29012.009050,0.000000,304338.748625,1497.84228,0.000000,0.000000,101019.634885,308265.171324,0.0,0.844840,93424.716616
PER.18.3,34694.749485,110800.019878,0.000000,14440.701940,2.737185e+06,0.975681,50110.499426,0.075068,31.019564,0.000000,7905.421177,0.000000,0.00000,0.000000,0.000000,222844.241306,8066.544323,0.0,390395.902352,13642.716095

#### ADMIN 2 diffs

In [42]:
np.abs(api_adm2 - qc_adm2) / qc_adm2 * 100

,Bare,Built-up,Cropland,Mangroves,Natural forests,Natural peat forests,Natural peat short vegetation,Natural short vegetation,Natural water,Non-natural bare,...,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural short vegetation,Non-natural tree cover,Non-natural water,Snow,Wetland natural forests,Wetland natural short vegetation,Wetland non-natural short vegetation,Wetland non-natural tree cover
aoi_id,,,,,,,,,,,,,,,,,,,,,
COD.6.10,0.023490,0.066644,0.126916,NaN,48.364360,0.132430,0.016469,0.126429,0.081168,0.000093,...,0.000508,0.000158,NaN,0.148471,NaN,NaN,0.140827,0.011141,0.000299,0.000124
IDN.14.13,0.006087,0.011610,0.003502,0.001446,7.789722,0.043879,0.022258,0.066134,0.022768,NaN,...,NaN,0.040897,NaN,0.077214,0.00568,NaN,0.000008,0.024655,NaN,NaN
PER.18.3,0.077145,0.156407,0.319683,NaN,9.606225,0.756438,0.051250,0.000057,0.072780,0.000048,...,0.000074,NaN,NaN,NaN,NaN,NaN,1.294296,0.127100,NaN,NaN

#### ⚠️ our api severely underestimating area for COD.6.10 and PER.18.3 and overestimates for IDN_14.13, the qc data total areas are accurate

In [45]:
api_adm1_results = {
    "data": {
        "result": {
            "natural_lands_class": [
                "Bare",
                "Built-up",
                "Cropland",
                "Mangroves",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Non-natural peat short vegetation",
                "Non-natural peat tree cover",
                "Non-natural tree cover",
                "Non-natural water",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Wetland non-natural short vegetation",
                "Wetland non-natural tree cover",
                "Bare",
                "Built-up",
                "Cropland",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Bare",
                "Built-up",
                "Cropland",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Non-natural peat short vegetation",
                "Non-natural peat tree cover",
                "Non-natural tree cover",
                "Snow",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Wetland non-natural short vegetation",
                "Wetland non-natural tree cover"
            ],
            "value": [
                105433799.171875,
                3193546406,
                17310028917.25,
                3107710903.75,
                38026067986.5,
                1245342471.7265625,
                118456585.45458984,
                362732607.078125,
                341682699.125,
                10945965.66015625,
                745295610.1047974,
                48583310.41949463,
                182948911.0078125,
                7755086996.943359,
                42971.00390625,
                564333845.2734375,
                57821696.90625,
                41416190.83642578,
                194561991.8791504,
                57667.96484375,
                407245568,
                10389292.1875,
                105014677504,
                2027106992,
                22241273.59375,
                565324782.375,
                707577671,
                96555161,
                313706.11767578125,
                2900950056,
                116999476,
                9434554919.574219,
                15181524976,
                39298168432.9375,
                57979634833.93506,
                16131503.309387207,
                11951312.3984375,
                137556010568.75,
                858957836.8828125,
                8632281.991760254,
                5093293364.922852,
                411464.32470703125,
                113906.18017578125,
                364087093.5446167,
                829743.4080810547,
                25814676.46710205,
                323363657.00097656,
                7274304.558898926,
                1406060.2522583008
            ],
            "aoi_id": [
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "MYS.13",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "SUR.9",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6",
                "USA.6"
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin"
            ]
        },
        "metadata": {
            "aoi": {
                "ids": [
                    "MYS.13",
                    "SUR.9",
                    "USA.6"
                ],
                "provider": "gadm",
                "type": "admin",
                "version": "4.1"
            }
        },
        "message": None,
        "status": "saved"
    },
    "status": "success"
}


api_adm1 = pd.DataFrame(api_adm1_results['data']['result'])
api_adm1.set_index('aoi_id', drop=True, inplace=True)
api_adm1.drop('aoi_type', inplace=True, axis=1)

In [47]:
api_adm1 = api_adm1.pivot(columns='natural_lands_class', values='value') / 1e4

In [48]:
api_adm1.head()

natural_lands_class,Bare,Built-up,Cropland,Mangroves,Natural forests,Natural peat forests,Natural peat short vegetation,Natural short vegetation,Natural water,Non-natural bare,Non-natural hhort vegetation,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural tree cover,Non-natural water,Snow,Wetland natural forests,Wetland natural short vegetation,Wetland non-natural short vegetation,Wetland non-natural tree cover
aoi_id,,,,,,,,,,,,,,,,,,,,
MYS.13,10543.379917,3.193546e+05,1.731003e+06,310771.090375,3.802607e+06,124534.247173,11845.658545,3.627326e+04,34168.269912,1094.596566,74529.561010,4858.331042,18294.891101,775508.699694,4.2971,NaN,56433.384527,5782.169691,4141.619084,19456.199188
SUR.9,5.766796,4.072456e+04,1.038929e+03,NaN,1.050147e+07,202710.699200,2224.127359,5.653248e+04,70757.767100,9655.516100,31.370612,NaN,NaN,NaN,NaN,NaN,290095.005600,11699.947600,NaN,NaN
USA.6,943455.491957,1.518152e+06,3.929817e+06,NaN,5.797963e+06,1613.150331,1195.131240,1.375560e+07,85895.783688,863.228199,509329.336492,41.146432,11.390618,36408.709354,NaN,82.974341,2581.467647,32336.365700,727.430456,140.606025

In [49]:
qc_adm1.head()

,Built-up,Cropland,Mangroves,Bare,Natural forests,Natural short vegetation,Natural water,Non-natural bare,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural short vegetation,Non-natural tree cover,Non-natural water,Wetland non-natural short vegetation,Wetland non-natural tree cover,Natural peat forests,Natural peat short vegetation,Snow,Wetland natural forests,Wetland natural short vegetation
GID_1,,,,,,,,,,,,,,,,,,,,
MYS.13,3.189895e+05,1.726807e+06,310087.3625,10542.823580,3.855625e+06,3.627098e+04,34149.881876,1094.597281,4857.856431,18288.005123,74493.019284,774089.661137,4.297098,4141.372605,19447.917727,124399.970840,11841.930998,0.000000,56399.759249,5780.415930
SUR.9,4.069954e+04,1.039009e+03,0.0000,5.766797,1.063286e+07,5.659118e+04,70739.939332,9656.267219,0.000000,0.000000,31.370515,0.000000,0.000000,0.000000,0.000000,202647.043063,2224.097486,0.000000,289845.353585,11704.319540
USA.6,1.519979e+06,3.917087e+06,0.0000,943520.133053,5.799869e+06,1.412279e+07,85892.513875,863.226009,41.146360,11.390599,509150.239717,36406.835437,0.000000,727.427139,140.605781,1613.148943,1195.130854,82.974248,2581.462142,32336.540573

In [50]:
np.abs(api_adm1 - qc_adm1) / qc_adm1 * 100

,Bare,Built-up,Cropland,Mangroves,Natural forests,Natural peat forests,Natural peat short vegetation,Natural short vegetation,Natural water,Non-natural bare,...,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural short vegetation,Non-natural tree cover,Non-natural water,Snow,Wetland natural forests,Wetland natural short vegetation,Wetland non-natural short vegetation,Wetland non-natural tree cover
aoi_id,,,,,,,,,,,,,,,,,,,,,
MYS.13,0.005277,0.114461,0.242968,0.220495,1.375089,0.107939,0.031478,0.006276,0.053845,0.000065,...,0.009770,0.037653,NaN,0.183317,0.000051,NaN,0.059620,0.030340,0.005952,0.042583
SUR.9,0.000009,0.061466,0.007640,NaN,1.235731,0.031412,0.001343,0.103726,0.025202,0.007779,...,NaN,NaN,NaN,NaN,NaN,NaN,0.086133,0.037353,NaN,NaN
USA.6,0.006851,0.120193,0.324971,NaN,0.032846,0.000086,0.000032,2.599994,0.003807,0.000254,...,0.000177,0.000164,NaN,0.005147,NaN,0.000111,0.000213,0.000541,0.000456,0.000174

In [51]:
api_adm0_results = {
    "data": {
        "result": {
            "natural_lands_class": [
                "Bare",
                "Built-up",
                "Cropland",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Non-natural peat short vegetation",
                "Non-natural peat tree cover",
                "Non-natural tree cover",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Wetland non-natural short vegetation",
                "Wetland non-natural tree cover",
                "Bare",
                "Built-up",
                "Cropland",
                "Mangroves",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Non-natural peat short vegetation",
                "Non-natural peat tree cover",
                "Non-natural tree cover",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Wetland non-natural short vegetation",
                "Wetland non-natural tree cover",
                "Bare",
                "Built-up",
                "Cropland",
                "Mangroves",
                "Natural forests",
                "Natural peat forests",
                "Natural peat short vegetation",
                "Natural short vegetation",
                "Natural water",
                "Non-natural bare",
                "Non-natural hhort vegetation",
                "Non-natural peat short vegetation",
                "Non-natural peat tree cover",
                "Non-natural tree cover",
                "Non-natural water",
                "Snow",
                "Wetland natural forests",
                "Wetland natural short vegetation",
                "Wetland non-natural short vegetation",
                "Wetland non-natural tree cover"
            ],
            "value": [
                59975639.48147583,
                19528375827,
                34351828602.37744,
                10469582114.697266,
                30816887.865997314,
                3206351.2367858887,
                894587388.6896667,
                689616905.7626953,
                664247.4885253906,
                1197419344.9073486,
                3271789.3542175293,
                76898279.12719727,
                11611250920.24939,
                34118492.14746094,
                16640756.181396484,
                2612076.690826416,
                24225677.81072998,
                17340107.359375,
                662173597.875,
                3654971555.3720703,
                645362302.0537109,
                1560293125.4375,
                4953751.701171875,
                231081499.203125,
                1955249399.2001953,
                295224186.1875,
                7775437.6416015625,
                704806431.1914062,
                2356836.2807006836,
                631059.2328491211,
                14934528.73828125,
                271068415.42089844,
                548534465.751709,
                96414852.72363281,
                2940798.1388549805,
                6985793987.066406,
                2191545091.6757812,
                4362214837.433594,
                49721724.900878906,
                80100797529.0625,
                752074112.8916016,
                491368994.9921875,
                74951333487.375,
                4628607849.1875,
                114421.17596435547,
                66550487504.52051,
                148495765.62304688,
                232594090.3564453,
                21304627461.015625,
                66391335.94238281,
                883536343.6235352,
                531652.4063720703,
                1705365377.7282715,
                1036618.9528808594,
                2700649.038757324
            ],
            "aoi_id": [
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "CZE",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "GMB",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL",
                "NZL"
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin"
            ]
        },
        "metadata": {
            "aoi": {
                "ids": [
                    "CZE",
                    "GMB",
                    "NZL"
                ],
                "provider": "gadm",
                "type": "admin",
                "version": "4.1"
            }
        },
        "message": None,
        "status": "saved"
    },
    "status": "success"
}

api_adm0 = pd.DataFrame(api_adm0_results['data']['result'])
api_adm0.set_index('aoi_id', drop=True, inplace=True)
api_adm0.drop('aoi_type', inplace=True, axis=1)

In [52]:
api_adm0 = api_adm0.pivot(columns='natural_lands_class', values='value') / 1e4

In [53]:
api_adm0

natural_lands_class,Bare,Built-up,Cropland,Mangroves,Natural forests,Natural peat forests,Natural peat short vegetation,Natural short vegetation,Natural water,Non-natural bare,Non-natural hhort vegetation,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural tree cover,Non-natural water,Snow,Wetland natural forests,Wetland natural short vegetation,Wetland non-natural short vegetation,Wetland non-natural tree cover
aoi_id,,,,,,,,,,,,,,,,,,,,
CZE,5997.563948,1.952838e+06,3.435183e+06,NaN,1.046958e+06,3081.688787,320.635124,8.945874e+04,68961.690576,66.424749,1.197419e+05,327.178935,7689.827913,1.161125e+06,NaN,NaN,3411.849215,1664.075618,261.207669,2422.567781
GMB,1734.010736,6.621736e+04,3.654972e+05,64536.230205,1.560293e+05,495.375170,23108.149920,1.955249e+05,29522.418619,777.543764,7.048064e+04,235.683628,63.105923,1.493453e+03,NaN,NaN,27106.841542,54853.446575,9641.485272,294.079814
NZL,698579.398707,2.191545e+05,4.362215e+05,4972.172490,8.010080e+06,75207.411289,49136.899499,7.495133e+06,462860.784919,11.442118,6.655049e+06,14849.576562,23259.409036,2.130463e+06,6639.133594,88353.634362,53.165241,170536.537773,103.661895,270.064904

In [54]:
qc_adm0

,Built-up,Cropland,Mangroves,Bare,Natural forests,Natural short vegetation,Natural water,Non-natural bare,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural short vegetation,Non-natural tree cover,Non-natural water,Wetland non-natural short vegetation,Wetland non-natural tree cover,Natural peat forests,Natural peat short vegetation,Snow,Wetland natural forests,Wetland natural short vegetation
GID_0,,,,,,,,,,,,,,,,,,,,
CZE,1.949909e+06,3.424003e+06,0.000000,5997.554592,1.046194e+06,8.946053e+04,68958.470097,66.424579,327.178151,7690.026690,1.197552e+05,1.160237e+06,0.000000,261.207068,2422.567151,3081.631632,320.634116,0.000000,3411.931035,1664.072004
GMB,6.620075e+04,3.652168e+05,64536.269984,1734.006235,1.559668e+05,1.953167e+05,29523.487672,777.541251,235.683531,63.105885,7.048583e+04,1.493453e+03,0.000000,9641.341800,294.079683,495.373737,23109.386759,0.000000,27104.599001,54856.014462
NZL,2.195007e+05,4.365640e+05,4969.745545,694356.517173,8.115791e+06,7.637555e+06,463095.351221,11.442088,14849.074635,23257.096589,6.696860e+06,2.130153e+06,6639.172187,103.543443,270.061188,75234.729006,49134.469143,88361.192901,53.046477,170505.023788

In [55]:
np.abs(api_adm0 - qc_adm0) / qc_adm0 * 100

,Bare,Built-up,Cropland,Mangroves,Natural forests,Natural peat forests,Natural peat short vegetation,Natural short vegetation,Natural water,Non-natural bare,...,Non-natural peat short vegetation,Non-natural peat tree cover,Non-natural short vegetation,Non-natural tree cover,Non-natural water,Snow,Wetland natural forests,Wetland natural short vegetation,Wetland non-natural short vegetation,Wetland non-natural tree cover
aoi_id,,,,,,,,,,,,,,,,,,,,,
CZE,0.000156,0.150199,0.326528,NaN,0.073004,0.001855,0.000314,0.001998,0.004670,0.000256,...,0.000240,0.002585,NaN,0.076574,NaN,NaN,0.002398,0.000217,0.000230,0.000026
GMB,0.000260,0.025083,0.076765,0.000062,0.040059,0.000289,0.005352,0.106596,0.003621,0.000323,...,0.000041,0.000061,NaN,0.000013,NaN,NaN,0.008274,0.004681,0.001488,0.000045
NZL,0.608172,0.157740,0.078463,0.048834,1.302532,0.036310,0.004946,1.864752,0.050652,0.000255,...,0.003380,0.009943,NaN,0.014546,0.000581,0.008554,0.223886,0.018483,0.114399,0.001376